/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DesignPattern;

import Database.Components.MsgBox;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Alim
 */
public abstract class JFrameInheritable extends JFrameDbComponents {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form InheritableJFrame
     */
    public JFrameInheritable() {
        setMessageBox(new MsgBox());
        initalizeTableName();
        initComponents();
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    public abstract void initalizeTableName();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  

    /**
     * Also points to previous form
     *
     * @param frame
     */
    public void loadNewForm(JFrameInheritable frame, boolean onTop) {
        loadNewForm(frame);
        frame.setAlwaysOnTop(true);
    }

    public void loadNewForm(JFrameInheritable frame, boolean onTop, boolean hideCurrentOne) {
        loadNewForm(frame, onTop);
        if (hideCurrentOne) {
            this.hide();
        }
    }

    public void loadNewForm(JFrameInheritable frame) {

        frame.show(true);
        frame.setPreviousForm(this);
        this.setNextForm(frame);
    }

    public JFrameInheritable getFrame(JPanel panel) {
        JFrameInheritable frame = new JFrameInheritable() {
            private static final long serialVersionUID = 1L;

            @Override
            public void initalizeTableName() {

            }
        };
        frame.setContentPane(panel);
        frame.pack();
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
        Dimension dimension = new Dimension(panel.getWidth(), panel.getHeight());
                
        frame.setPreferredSize(dimension);
        return frame;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
