/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DesignPattern;

import CurrentDb.Tables.FriendRequestTable;
import Database.Components.MsgBox;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Alim
 */
public abstract class JFrameInheritable extends JFrameDbComponents {

    private static final long serialVersionUID = 1L;

    //DefaultListModel<T> displayModel = new DefaultListModel();

    public void terminateCurrentForm(boolean loadPreviousForm) {
        this.hide();
        if (loadPreviousForm) {
            this.getPreviousForm().show(true);
        }
        dispose();
    }

    /**
     * Creates new form InheritableJFrame
     */
    public JFrameInheritable() {
        setMessageBox(new MsgBox());
        initalizeTableName();
        initComponents();
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    protected void initUI(JFrameInheritable frame) {

        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        final JComboBox<LookAndFeelInfo> laf = new JComboBox<LookAndFeelInfo>();
        LookAndFeelInfo selected = null;
        for (LookAndFeelInfo lafInfo : UIManager.getInstalledLookAndFeels()) {
            laf.addItem(lafInfo);
            if (lafInfo.getName().equals(UIManager.getLookAndFeel().getName())) {
                selected = lafInfo;
            }
        }
        laf.setSelectedItem(selected);
        laf.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                if (value != null) {
                    LookAndFeelInfo lafInfo = (LookAndFeelInfo) value;
                    setText(lafInfo.getName());
                } else {
                    setText("");
                }
                return this;
            }
        });
        laf.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                String className = laf.getModel().getElementAt(laf.getSelectedIndex()).getClassName();
                System.err.println("Changing to " + className);
                try {
                    UIManager.setLookAndFeel(className);
                    SwingUtilities.updateComponentTreeUI(frame.getRootPane());
                } catch (ClassNotFoundException e1) {
                    e1.printStackTrace();
                } catch (InstantiationException e1) {
                    e1.printStackTrace();
                } catch (IllegalAccessException e1) {
                    e1.printStackTrace();
                } catch (UnsupportedLookAndFeelException e1) {
                    e1.printStackTrace();
                }
            }

        });
        frame.add(laf);

        frame.setVisible(true);
    }

    public abstract void initalizeTableName();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Jframe related code">
    /**
     * Also points to previous form
     *
     * @param frame
     * @param onTop
     */
    public void loadNewForm(JFrameInheritable frame, boolean onTop) {
        loadNewForm(frame);
        frame.setAlwaysOnTop(true);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);

    }

    public void loadNewForm(JFrameInheritable frame, boolean onTop, boolean hideCurrentOne) {
        loadNewForm(frame, onTop);
        if (hideCurrentOne) {
            this.hide();
        }
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);

    }

    public void loadNewForm(JFrameInheritable frame) {

        frame.show(true);
        frame.setPreviousForm(this);
        this.setNextForm(frame);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    public JFrameInheritable getFrame(final JPanelDbInheritable panel) {
        JFrameInheritable frame = new JFrameInheritable() {
            private static final long serialVersionUID = 1L;

            @Override
            public void initalizeTableName() {
                panel.initalizeTableName();
            }
        };
        frame.setContentPane(panel);
        frame.pack();
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
        Dimension dimension = new Dimension(panel.getWidth(), panel.getHeight());

        frame.setPreferredSize(dimension);
        return frame;
    }
    //</editor-fold>
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
