/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SimpleChatSystem;

import CurrentDb.TableColumns.FriendRequest;
import CurrentDb.TableNames;
import CurrentDb.Tables.UserTable;
import DesignPattern.JFrameInheritable;
import Mailer.OwnGmail;

/**
 *
 * @author Alim
 */
public class AddFriend extends JFrameInheritable {

    private ListOfFriends _listOfFriendsForm;
    private UserTable _sendingToUser;
    private UserTable _sendingFromUser;
    OwnGmail mailer = new OwnGmail();

    /**
     * Creates new form AddFriend
     */
    public AddFriend(UserTable sendingToUser, UserTable sendingFromUser) {

        initComponents();

        _sendingToUser = sendingToUser;
        _sendingFromUser = sendingFromUser;
        _sendingToUser.displayUser(this.ToUser_UsernameLabel, this.ToUser_UserStatusLabel, null, this.ToUser_ProfilePicture);
        this.setTitle("Add friend : " + _sendingToUser.Username);
    }

    public boolean isFriendRequsetAlreadySent() {
        this.getDb().setTableName(TableNames.FRIEND_REQUEST);
        byte row = 2;
        String[] columns = new String[row];
        String[] values = new String[row];

        columns[--row] = FriendRequest.SenderUserID;
        values[row] = _sendingFromUser.UserID + "";

        columns[--row] = FriendRequest.ToWhomUserID;
        values[row] = _sendingToUser.UserID + "";

        return this.getDb().isExist(columns, values);

    }

    /**
     *
     * @return true means just sent. false means request is already sent or
     * failed.
     */
    public boolean addFriendRequesToUserDb() {
        if (isFriendRequsetAlreadySent() == false) {
            byte row = 4;
            String[] columns = new String[row];
            String[] values = new String[row];

            columns[--row] = FriendRequest.SenderUserID;
            values[row] = _sendingFromUser.UserID + "";

            columns[--row] = FriendRequest.ToWhomUserID;
            values[row] = _sendingToUser.UserID + "";

            columns[--row] = FriendRequest.IsAccept;
            values[row] = "0";

            columns[--row] = FriendRequest.Message;
            values[row] = this.quoteTextBox.getText();
            if (this.getDb().insertData(columns, values)) {
                this.getMessageBox().show(this, "Successfully friend request sent!");
                return true;
            }

        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToUser_ProfilePicture = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ToUser_UsernameLabel = new javax.swing.JLabel();
        ToUser_UserStatusLabel = new javax.swing.JLabel();
        quoteTextBox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ToUser_ProfilePicture.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Add Friend");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ToUser_UsernameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ToUser_UsernameLabel.setText("Username");

        ToUser_UserStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ToUser_UserStatusLabel.setText("Status");

        quoteTextBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        quoteTextBox.setToolTipText("Message to accept your request");
        quoteTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quoteTextBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quoteTextBox)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ToUser_ProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ToUser_UsernameLabel)
                                    .addComponent(ToUser_UserStatusLabel)))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 236, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToUser_ProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ToUser_UsernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToUser_UserStatusLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quoteTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void sendMailToUser() {
        String body = "";
        body += "Hello " + _sendingToUser.Name + ", <br>";
        body += "How you doing? Someone personal try to add you in his/her friend list. <br>";
        body += "<br>";
        body += "<h3>A short message from " + _sendingFromUser.Username + "</h3>";
        body += "<quote>" + this.quoteTextBox + "</quote>";
        body += "<br><br>";
        body += "Thanks ,";
        body += "<strong>" + _sendingFromUser.Username + "</strong>";
        body += "<a href='mailto:" + _sendingFromUser.Email + "'>" + _sendingFromUser.Email + "</strong>";
        mailer.sendEmail(_sendingToUser.Email, "A friend request is send by " + _sendingFromUser.Username, body);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (addFriendRequesToUserDb()) {
            sendMailToUser();
            this.hide();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        getPreviousForm().show(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void quoteTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quoteTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quoteTextBoxActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ToUser_ProfilePicture;
    private javax.swing.JLabel ToUser_UserStatusLabel;
    private javax.swing.JLabel ToUser_UsernameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField quoteTextBox;
    // End of variables declaration//GEN-END:variables
    @Override
    public void initalizeTableName() {

    }

    /**
     * @return the _listOfFriendsForm
     */
    public ListOfFriends getListOfFriendsForm() {
        return _listOfFriendsForm;
    }

    /**
     * @param _listOfFriendsForm the _listOfFriendsForm to set
     */
    public void setListOfFriendsForm(ListOfFriends _listOfFriendsForm) {
        this._listOfFriendsForm = _listOfFriendsForm;
    }

}
